# @Author: callback
# @Date:   2016-09-23T16:05:57+08:00
# @Email:  heuuLZP@gmail.com
# @Last modified by:   callback
# @Last modified time: 2016-09-25T20:44:09+08:00
baseurl: 
markdown: kramdown
kramdown:
  input: GFM
